patterns_dict = {
    'NET CORE': r'\b.NET\sCORE\b',
    'APS.NET': r'\bASP.NET\b',
    'AWS Elastic Load Balancing': r'\bAWS\sElastic\sLoad\sBalancing\s',
    'AWS Lambda': r'\bAWS\sLambda\b',
    'Amazon CloudFront': r'\bAmazon\sCloudFront\b',
    'Amazon CloudWatch': r'\bAmazon\sCloudWatch\b',
    'Amazon EC2': r'\bAmazon\sEC2\b',
    'Amazon EC2 Container Service': r'\bAmazon\sEC2\sContainer\sService\b',
    'Amazon RDS': r'\bAmazon\sRDS\b',
    'Amazon Route 53': r'\bAmazon\sRoute\s53\b',
    'Amazon S3': r'\bAmazon\sS3\b',
    'Amazon SES': r'\bAmazon\sSES\b',
    'Android SDK': r'\bAndroid\sSDK\b',
    'Android Studio': r'\bAndroid\sStudio\b',
    'Angular': r'\bAngular\b',
    'Animate.css': r'\bAnimate.css\b',
    'AnimeJS': r'\bAnimeJS\b',
    'Ansible': r'\bAnsible\b',
    'Apache HTTP Server': r'\bApache\sHTTP\sServer\b',
    'Apache Tomcat': r'\bApache\sTomcat\b',
    'Asana': r'\bAsana\b',
    'Atom': r'\bAtom\b',
    'Babel': r'\bBabel\b',
    'Backbone.js': r'\bBackbone.js\b',
    'Bitbucket': r'\bBitbucket\b',
    'BootStrap': r'\bBootStrap\b',
    'Bower': r'\bBower\b',
    'C#' : r'\bC#\b',
    'CSS3': r'\bCSS\s3\b',
    'Cassandra': r'\bCassandra\b',
    'CentOS': r'\bCentOS\b',
    'CircleCI': r'\bCircleCI\b',
    'Chart.JS': r'\bChart.JS\b',
    'CloudFlare': r'\bCloudFlare\b',
    'Confluence': r'\bConfluence\b',
    'D3': r'\bD3\b',
    'Datadog': r'\bDatadog\b',
    'Debian': r'\bDebian\b',
    'DigitalOcean': r'\bDigitalOcean\b',
    'Django': r'\bDjango\b',
    'Docker': r'\bDocker\b',
    'Docker Compose': r'\bDocker\sCompose\b',
    'ES6': r'\bES6\b',
    'ESLint': r'\bESLint\b',
    'Elasticsearch': r'\bElasticsearch\b',
    'Electron': r'\bElectron\b',
    'ExpressJS': r'\bExpressJS?\b',# special regex needed
    'Firebase': r'\bFirebase\b',
    'Flask': r'\bFlask\b',
    'Flutter': r'\bFlutter\b',
    'FullPageJS': r'\bFullPageJS?\b',# special regex needed
    'G Suite': r'\bG\sSuite\b',
    'Git': r'\bGit\b',
    'GitHub': r'\bGitHub\b',
    'GitHub Pages': r'\bGitHub\sPages\b',
    'GitLab': r'\bGitLab\b',
    'Glimmer': r'\bGlimmer\b',
    'Google AdSense': r'\bGoogle\sAdSense\b',
    'Google Analytics': r'\bGoogle\sAnalytics\b',
    'Google App Engine': r'\bGoogle\sApp\sEngine\b',
    'Google Cloud Platform': r'\bGoogle\sCloud\sPlatform\b',
    'Google Compute Engine': r'\bGoogle\sCompute\sEngine\b',
    'Google Tag Manager': r'\bGoogle\sTag\sManager\b',
    'Gradle': r'\bGradle\b',
    'Grafana': r'\bGrafana\b',
    'GrapQL': r'\bGraphQL\b',
    'Groovy': r'\bGroovy\b',
    'Grunt': r'\bGrunt\b',
    'HTML5': r'\bHTML5\b',
    'Hadoop': r'\bHadoop\b',
    'Handlebars': r'\bHandlebars.js\b',
    'Heroku': r'\bHeroku\b',
    'HubSpot': r'\bHubSpot\b',
    'InVision': r'\bInVision\b',
    'IntelliJ IDEA': r'\bIntelliJ\sIDEA\b',
    'Intercom': r'\bIntercom\b',
    'Ionic':r' \bIonic\b',
    'Java': r'\bJava\b',
    'JavaScript': r'\bJavaScript\b',
    'Jenkins': r'\bJenkins\b',
    'Jira': r'\bJira\b',
    'Kafka': r'\bKafka\b',
    'Kibana': r'\bKibana\b',
    'Kotlin': r'\bKotlin\b',
    'Kebernetes': r'\bKubernetes\b',
    'Laravel': r'\bLaravel\b',
    'Leaflet': r'\bLeaflet\b',
    'Lodash': r'\bLodash\b',
    'Logstash': r'\bLogstash\b',
    'Mailgun': r'\bMailgun\b',
    'MariaDB': r'\bMariaDB\b',
    'Markdown': r'\bMarkdown\b',
    'Matlab': r'\bMatLab\b',
    'Material Design for Angular': r'\bMaterial\sDesign\sfor\sAngular\b',
    'Memchached': r'\bMemcached\b',
    'Microsoft Azure': r'\bMicrosoft\sAzure\b',
    'Microsoft IIS': r'\bMicrosoft\sIIS\b',
    'Microsoft SQL Server': r'\bMicrosoft\sSQL\sServer\b',
    'Mixpanel': r'\bMixpanel\b',
    'Modernizr': r'\bModernizr\b',
    'MongoDB': r'\bMongoDB\b',
    'MySQL': r'\bMySQL\b',
    'NGINX': r'\bNGINX\b',
    'New Relic': r'\bNew\sRelic\b',
    'Next.JS': r'\bNext.JS\b',
    'NoSQL': r'\bNoSQL\b',
    'Node.js': r'\bNode.js\b', # special regex needed
    'Notepad++': r'\bNotepad\+\+\b', # special regex needed
    'Objective-C': r'\bObjective-C\b',
    'OpenSSL': r'\bOpenSSL\b',
    'Oracle': r'\bOracle\b',
    'PHP': r'\bPHP\b',
    'PayPal': r'\bPayPal\b',
    'Perl': r'\bPerl\b',
    'PhpStorm': r'\bPhpStorm\b',
    'PostgreSQL': r'\bPostgreSQL\b',
    'Postman': r'\bPostman\b',
    'Polymer': r'\bPolymer\b',
    'PyCharm': r'\bPyCharm\b',
    'Python': r'\bPython\b',
    'RabbitMQ': r'\bRabbitMQ\b',
    'Rails': r'\bRails\b',
    'React': r'\bReact\b',
    'React Native': r'\bReact\sNative\b',
    'Redis': r'\bRedis\b',
    'Redux': r'\bRedux\b',
    'RequireJS': r'\bRequireJS\b',
    'Ruby': r'\bRuby\b',
    'SQL': r'\bSQL\b',
    'SQLite': r'\bSQLite\b',
    'Sass': r'\bSass\b',
    'Scala': r'\bScala\b',
    'Selenium': r'\bSelenium\b',
    'Sentry': r'\bSentry\b',
    'Shopify': r'\bShopify\b',
    'Skype': r'\bSkype\b',
    'Slack': r'\bSlack\b',
    'Slick': r'\bSlick\b',
    'Socket.IO': r'\bSocket.IO\b', # special regex needed
    'SourceTree': r'\bSourceTree\b',
    'Spring Boot': r'\bSpring\sBoot\b',
    'Stack Overflow': r'\bStack\sOverflow\b',
    'Stripe': r'\bStripe\b',
    'Sublime Text': r'\bSublime\sText\b',
    'Swift': r'\bSwift\b',
    'Symfony': r'\bSymfony\b',
    'TensorFlow': r'\bTensorFlow\b',
    'Terraform': r'\bTerraform\b',
    'Travis CI': r'\bTravis\sCI\b',
    'Trello': r'\bTrello\b',
    'Twilio': r'\bTwilio\b',
    'Twilio SendGrid': r'\bTwilio\sSendGrid\b',
    'TypeScript': r'\bTypeScript\b',
    'Ubuntu': r'\bUbuntu\b',
    'Vagrant': r'\bVagrant\b',
    'Varnish': r'\bVarnish\b',
    'Vim': r'\bVim\b',
    'VirtualBox': r'\bVirtualBox\b',
    'Visual Studio': r'\bVisual\sStudio\b',
    'Visual Studio Code': r'\bVisual\sStudio\sCode\b',
    'Vue.js': r'\bVue\.js\b', # special regex needed
    'Webpack': r'\bWebpack\b',
    'WebStorm': r'\bWebStorm\b',
    'WooCommerce': r'\bWooCommerce\b',
    'WordPress': r'\bWordPress\b',
    'Xamarin': r'\bXamarin\b',
    'Xcode': r'\bXcode\b',
    'Yarn': r'\bYarn\b',
    'Zendesk': r'\bZendesk\b',
    'gulp': r'\bgulp\b',
    'jQuery': r'\bjQuery\b',
    'jQuery UI': r'\bjQuery\sUI\b',
    'npm': r'\bnpm\b'
    }
